# Generated by Django 5.0.3 on 2024-07-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
