# Generated by Django 5.0.3 on 2024-07-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
