# Generated by Django 5.0.3 on 2024-07-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_details_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='objective',
            field=models.TextField(null=True),
        ),
    ]
