# Generated by Django 5.0.3 on 2024-07-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_skills_other_alter_skills_cloud_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='version_control',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
