# Generated by Django 5.0.3 on 2024-08-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_certificates_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='skills_used',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
