# Generated by Django 5.0.3 on 2024-08-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_projects_skills_used_alter_projects_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='task',
            field=models.TextField(null=True),
        ),
    ]
