# Generated by Django 5.0.3 on 2024-08-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_experience_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
